# basic settings

config                      = "config.toml"
log                         =  true
verbose                     =  true
logFile                     = "hugo.log" 
verboseLog                  = "info.log"
ignoreFiles                 = [ "\\.cmd$", "\\.log$", "\\.bat$", "\\.tmp$" , "\\.swp$"]
timeout                     = 300000

#baseUrl                    = "http://localhost:1313"
disableKinds                = ["RSS", "sitemap"]
refLinksNotFoundURL        = "/404.html"

title                       = "G's Playground"
titleCaseStyle              = "Chicago"
theme                       = "photon"

###############################################################

LanguageCode                   = "de-de"
DefaultContentLanguage         = "de"
DefaultContentLanguageInSubdir = true
defaultExtension           = "html"
defaultLayout              = "post"

###############################################################

archetypedir               = "archetypes"
assetdir                   = "assets"
contentdir                 = "content"
dataDir                    = "data"
layoutdir                  = "layouts"
publishdir                 = "public"
paginatepath               = "page"
resourcedir                = "resources"
staticdir                  = "static"

###############################################################

buildDrafts                = false
buildExpired               = false
buildFuture                = false
canonifyURLs               = false
disableAliases             = false
cleandestinationdir        = true
disableHugoGeneratorInject = true
disablePathToLower         = false
enableGitInfo              = true
enableRobotsTXT            = true
ignorecache                = false
forceSyncStatic            = false
#pluralizelisttitles       = false
relativeURLs               = false
removePathAccents          = true
summaryLength              = 10
taskLists                  = false

###############################################################

[frontmatter]
date                       = [ "date", ":filename", ":default"]
publishDate                = [ "publishDate", "date"]
lastmod                    = [ ":git", "lastmod", ":fileModTime", "publishDate"]
expiryDate                 = [ "expiryDate"]

###############################################################

[_build]
  publishResources = false

###############################################################

[markup]
  defaultMarkdownHandler = "goldmark"
  
### https://github.com/yuin/goldmark/#built-in-extensions

  [markup.goldmark]
    [markup.goldmark.extensions]
	  autolinks      = false
      definitionList = false
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = false
      typographer    = true
    [markup.goldmark.parser]
#      autoHeadingID     = false
#      autoHeadingIDType = "github"
       withAttribute     = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
      xhtml  = true
      hardWraps = false

###############################################################

# https://github.com/tdewolff/minify#html
[minify] 
# HTML
    minifyOutput             = false
    KeepComments             = false
    KeepConditionalComments  = false
    KeepWhitespace           = false
    KeepDefaultAttrVals      = false
    KeepEndTags              = true
    KeepQuotes               = false   # HTML5!    
# JSON
    KeepNumbers              = true

###############################################################

[taxonomies]
    tag                    = "tags"
    serie                  = "series"
#   categorie NOT used!

###############################################################


[outputs]
    home                   = [ "HTML", "ATOM", "JSON", "FEED", "MANIFEST", "SITEMAP", "SEARCH"]
    section               = [ "HTML", "SITEMAP" ]
    page                  = [ "HTML" ]
    taxonomy              = [ "HTML" ]
    taxonomyTerm          = [ "HTML" ]

###############################################################


[Author]
    name               = "Mr. Nobody"
    email              = "me@example.com"

###############################################################

[Params]
    title              = "My Playground"
    copyright          = "Mr. Nobody"
    copyrightyear      = "2000"

# Doubline Core
    Creator                = "lastname, firstname"
    Publisher              = "lastname, firstname"


[Params.sidebar]
    avatar          = "images/head.jpg"
    bio             = "**Mr. Nobody**"

[Params.Sitemap]
    changeFreq = "weekly"
    priority   = 0.5
