# basic settings

config                      = "config.toml"
log                         =  true
verbose                     =  true
logFile                     = "hugo.log" 
verboseLog                  = "info.log"
ignoreFiles                 = [ "\\.cmd$", "\\.log$", "\\.bat$", "\\.tmp$" , "\\.swp$"]
timeout                     = 300000

#baseUrl                    = "http://localhost:1313"
refLinksNotFoundURL        = "/404.html"

title                       = "G's Playground"
titleCaseStyle              = "Chicago"
theme                       = "photon"

disableKinds                = ["RSS", "sitemap"]

###############################################################

LanguageCode                   = "de-de"
DefaultContentLanguage         = "de"
DefaultContentLanguageInSubdir = true
defaultExtension           = "html"
defaultLayout              = "post"
#timeZone                  = "Europa/Berlin"  # indirect from DefaultContentLanguage

###############################################################

archetypedir               = "archetypes"
assetdir                   = "assets"
contentdir                 = "content"
dataDir                    = "data"
layoutdir                  = "layouts"
publishdir                 = "public"
paginatepath               = "page"
resourcedir                = "resources"
staticdir                  = "static"

###############################################################

buildDrafts                = false
buildExpired               = false
buildFuture                = false
canonifyURLs               = false
disableAliases             = false
cleandestinationdir        = true
disableHugoGeneratorInject = true
disablePathToLower         = false
enableGitInfo              = true
enableRobotsTXT            = true
ignorecache                = false
forceSyncStatic            = false
#pluralizelisttitles       = false
publishResources           = false
pygmentsUseClasses         = true
pygmentsCodefences         = true
relativeURLs               = false
removePathAccents          = true
summaryLength              = 10
taskLists                  = false

###############################################################

[frontmatter]
date                       = [ "date", ":filename", ":default"]
publishDate                = [ "publishDate", "date"]
lastmod                    = [ ":git", "lastmod", ":fileModTime", "publishDate"]
expiryDate                 = [ "expiryDate"]

###############################################################

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^notepad...exe$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|SSH_AUTH_SOCK|USERPROFILE|XDG_CONFIG_HOME)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

###############################################################
#
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

[Params.csp]
  base-uri    = ["'self'"]
  default-src = ["https:",  "'self'"]
  script-src  = ["'self'", "https://cdn.jsdelivr.net", "https://polyfill.io", "NONCE"]
  frame-src   = ["https://*.youtube.com"]
  style-src   = ["'self'", "'unsafe-inline'"]

#  form-action = ["'none'"] 
#  connect-src = ["'self'"]
#  img-src     = ["'self'"]
#  manifest-src= ["'self'"]
#  object-src  = ["'self'"]
###############################################################

[_build]
  publishResources = false
  _merge           = "deep"

###############################################################

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

###############################################################

[markup]
  defaultMarkdownHandler = "goldmark"
       
    [markup.goldmark.renderer]
      unsafe = true
      xhtml  = true
      hardWraps = false
      WithAttribute  = true

    [markup.highlight]
      anchorLineNos = false
      codeFences    = true
      guessSyntax   = false
      hl_Lines      = ""
      lineAnchors   = ""
      lineNoStart   = 1
      lineNos       = true
      lineNumbersInTable = true
      noClasses     = false
      tabWidth      = 2

###############################################################

[taxonomies]
    tag                    = "tags"
    serie                  = "series"
#   category NOT used!

###############################################################

[outputs]
    home                   = [ "HTML", "ATOM", "JSON", "FEED", "MANIFEST", "SITEMAP", "SEARCH"]
    section               = [ "HTML", "SITEMAP" ]
    page                  = [ "HTML" ]
    taxonomy              = [ "HTML" ]
    taxonomyTerm          = [ "HTML" ]

###############################################################

[permalinks]
    post                   = "/:section/:year/:month/:day/:title"
    photo                  = "/:section/:year/:month/:day/:title"
    book                   = "/:sections/:slug"
    series                 = "/:section/:slug"
    tags                   = "/:section/:slug"
    about                  = "/:section/:slug"
    search                 = "/:section/:slug"
    intern                 = "/:section/:year/:month/:day/:title"
    test                   = "/:section/:title"
      
###############################################################

[Author]
    name               = "Mr. Nobody"
    email              = "me@example.com"

###############################################################

[Params]
    title              = "My Playground"
    copyright          = "Mr. Nobody"
    copyrightyear      = "2000"

# Doubline Core
    Creator                = "lastname, firstname"
    Publisher              = "lastname, firstname"

    feedSize               = 50 # rssLimit

[Params.sidebar]
    avatar          = "img/head.jpg"
    avatarSize      = 80
    avatarQuality          = "q80"
    bio             = "**Mr. Nobody**"

