# basic site settings

config                      = "hugo.toml"
log                         =  true
verbose                     =  true
logFile                     = "hugo.log" 
verboseLog                  = "info.log"
ignoreFiles                 = [ "\\.cmd$", "\\.log$", "\\.bat$", "\\.tmp$" , "\\.swp$", "\\.url$"]
timeout                     = 300000

refLinksNotFoundURL        = "/404.html"

title                       = "G's Playground"
titleCaseStyle              = "Chicago"
theme                       = "photon"

disableKinds                = ["RSS", "sitemap"]

###############################################################

LanguageCode                   = "de-de"
DefaultContentLanguage         = "de"
DefaultContentLanguageInSubdir = false
defaultExtension           = "html"
defaultLayout              = "post"
#timeZone                  = "Europa/Berlin"  # indirect from DefaultContentLanguage

###############################################################


buildDrafts                = false
buildExpired               = false
buildFuture                = false
canonifyURLs               = false
disableAliases             = false
cleandestinationdir        = true
disableHugoGeneratorInject = true
disablePathToLower         = false
enableGitInfo              = true
enableRobotsTXT            = true
ignorecache                = false
forceSyncStatic            = false
#pluralizelisttitles       = false
publishResources           = false
pygmentsUseClasses         = true
pygmentsCodefences         = true
relativeURLs               = false
removePathAccents          = true
summaryLength              = 10
taskLists                  = false

###############################################################

[frontmatter]
date                       = [ "date", ":filename", ":default"]
publishDate                = [ "publishDate", "date"]
lastmod                    = [ ":git", "lastmod", ":fileModTime", "publishDate"]
expiryDate                 = [ "expiryDate"]

###############################################################

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^notepad...exe$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

###############################################################
#
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

[Params.csp]
  base-uri    = ["'self'"]
  default-src = ["https:",  "'self'"]
  script-src  = ["'self'", "https://cdn.jsdelivr.net", "https://polyfill.io", "NONCE"]
  frame-src   = ["https://*.youtube.com"]
  style-src   = ["'self'", "'unsafe-inline'"]

#  form-action = ["'none'"] 
#  connect-src = ["'self'"]
#  img-src     = ["'self'"]
#  manifest-src= ["'self'"]
#  object-src  = ["'self'"]
###############################################################

[_build]
  publishResources = false
  _merge           = "deep"

###############################################################

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

# https://gohugo.io/getting-started/configuration/#configure-http-cache
[httpcache]
  [httpcache.cache]
    [httpcache.cache.for]
      includes = ['https://img.youtube.com/**']
# activating the next 2 lines crashes version 0.145
#    [[httpcache.polls]]
#      disable = true

###############################################################

[markup]
  defaultMarkdownHandler = "goldmark"
       
    [markup.goldmark.renderer]
      unsafe = true
      xhtml  = false
      hardWraps = false

    [markup.goldmark.parser]
       withAttribute     = true
       wrapStandAloneImageWithinParagraph = false

       [markup.goldmark.parser.attribute]
         block = true

### https://github.com/yuin/goldmark/#built-in-extensions
    [markup.goldmark.extensions]
      autolinks      = false
      definitionList = false
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = false
      typographer    = true      

      [markup.goldmark.extensions.passthrough]
        enable      = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block    = [['\[', '\]'], ['$$', '$$']]
          inline   = [['\(', '\)'], ['$', '$']]

      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true



    [markup.highlight]
      anchorLineNos = false
      codeFences    = true
      guessSyntax   = false
      hl_Lines      = ""
      lineAnchors   = ""
      lineNoStart   = 1
      lineNos       = true
      lineNumbersInTable = true
      noClasses     = false
      tabWidth      = 2

###############################################################


[sitemap]
  changefreq = "weekly"
  priority = 0.5

###############################################################

[taxonomies]
    tag                    = "tags"
    serie                  = "series"
#   category NOT used!

###############################################################

[outputs]
    home                   = [ "HTML", "ATOM", "JSON", "FEED", "MANIFEST", "SITEMAP", "SEARCH"]
    section               = [ "HTML", "SITEMAP" ]
    page                  = [ "HTML" ]
    taxonomy              = [ "HTML" ]

###############################################################
# after V115.x!

[permalinks]

    about                  = "/:section/"
    search                 = "/:section/"   
    link                   = "/:section/"   

    post                   = "/:section/:year/:month/:day/:title"
    photo                  = "/:section/:year/:month/:day/:title"
    book                   = "/:sections/:slug/"
    intern                 = "/:section/:year/:month/:day/:title"
    test                   = "/:section/:title"


    tags                   = "/:section/:slug"
    series                 = "/:section/:slug"

###############################################################

[Params]
    title              = "My Playground"
    copyright          = "Mr. Nobody"
    copyrightyear      = "2000"
    description        = "technological extract from my production site"

# Doubline Core
    Creator                = "lastname, firstname"
    Publisher              = "lastname, firstname"

# RSS, ATOM & JSON FEED
    feedSize               = 50 # rssLimit

###############################################################

[Params.Author]
    name               = "Mr. Nobody"
    email              = "me@example.com"
	
[Params.sidebar]
    avatar          = "img/head.jpg"
    avatarSize      = 80
    avatarQuality          = "q80"
    bio             = "**Mr. Nobody**"
