# theme configuration

disableKinds               = ["RSS", "sitemap"]

[Params.Pagination]
    PagesPerList           = 10
    PagesPerListHome       = 12
    Paginate               = 10
    firstIndicator         = "<i class=\"fas fa-angle-double-left\"></i>"
    previousIndicator      = "<i class=\"fas fa-angle-left\"></i>"
    nextIndicator          = "<i class=\"fas fa-angle-right\"></i>"
    lastIndicator          = "<i class=\"fas fa-angle-double-right\"></i>"
    showBeginEnd           = false
    spaceIndicator         = "<b> ... </b>"
    pagesBetweenActive     = 5
	
	
################# Image handling ###########
# shortcode   figure.html
# render hook render-image.html

[Params.Images]
    maxSize               = 1480
    setSizes              = [ 480, 800, 1200 ]
    sizes                 = "sizes=(max-width: 30em) 90vw, (max-width: 60em) 80vw, 1480px"

###############################################################	

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/rss+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/json"]
    suffixes               = ["json"]

# search
  [mediaTypes."application/json-catalog"]
    suffixes               = ["catalog"]

  [mediaTypes."application/manifest+json"]
    suffixes               = ["webmanifest"]

[outputFormats.HTML]
    baseName               = "index"
    NoUgly                 = true
    IsHTML                 = true
    permalinkable          = true

[outputFormats.ATOM]
    MediaType              = "application/atom+xml"
    BaseName               = "feeds/feed.atom"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.FEED]       ##### ==> no collision with buildin RSS!
    MediaType              = "application/rss+xml"
    BaseName               = "feeds/feed.rss"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.JSON]
    MediaType              = "application/json"
    BaseName               = "feeds/feed"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    Rel                    = "alternate"

[outputFormats.SITEMAP]
    MediaType              = "application/xml"
    BaseName               = "sitemap"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    notAlternative         = true
    Rel                    = "sitemap"


[outputFormats.MANIFEST]
    MediaType              = "application/manifest+json"
    BaseName               = "manifest"
    suffix                 = "webmanifest"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    notAlternative         = true
    Rel                    = "manifest"

[outputFormats.SEARCH]
    MediaType              = "application/json-catalog"
    BaseName               = "search/search"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    notAlternative         = true
    Rel                    = "alternate"

[imaging]
    resampleFilter         = "Lanczos"
    quality                = 85
    bgColor                = "#ffffff"

[imaging.exif]
    includeFields = ".*"

[Params]
    published              = "2016-08-21T00:00:00Z"
    dateFormatLong         = "2006-01-02 15:04"
    dateFormatShort        = "2006-01-02"
    dateFormatYear         = "2006"
    dateFormatFeed         = "2006-01-02T15:04:05Z"
	dateFormatISO8601      = "2006-01-02T15:04:05-07:00" 
    dateFormatRFC822Z      = "02 Jan 2006 15:04:05 UT"

    invisibleSections      = ["intern","test","about","links","search"]
    sitemapMax             = 49999

    digest                 = "sha384" # sha256, sha384, sha512
	

[menus]
[[menus.main]]
    identifier             = "home"
    name                   = "Home"
    url                    = "/"
    weight                 = 10

[[menus.main]]
    identifier             = "post"
    name                   = "Posts"
    url                    = "/post/"
    weight                 = 20

[[menus.main]]
    identifier             = "photo"
    name                   = "Photos"
    url                    = "/photo/"
    weight                 = 30

[[menus.main]]
    identifier             = "serie"
    name                   = "Series"
    url                    = "/series/"
    weight                 = 40

[[menus.main]]
    identifier             = "link"
    name                   = "Links"
    url                    = "/links/"
    weight                 = 100

[[menus.main]]
    identifier             = "index"
    name                   = "Index"
    url                    = "/tags/"
    weight                 = 110

[[menus.main]]
    identifier             = "search"
    name                   = "Search"
    url                    = "/search/"
    weight                 = 110

[[menus.main]]
    identifier             = "divider1"
    weight                 = 120
	
[[menus.main]]
    identifier             = "feeds"
    name                   = "Feeds"
    url                    = "/feeds/"
    weight                 = 130
	
[[menus.main]]
    identifier             = "rss"
	parent                 = "feeds"
    name                   = "RSS"
    url                    = "/feeds/feed.rss.xml"
    weight                 = 131

[[menus.main]]
    identifier             = "atom"
	parent                 = "feeds"
    name                   = "ATOM"
    url                    = "/feeds/feed.atom.xml"
    weight                 = 132
	
[[menus.main]]
    identifier             = "JSON"
	parent                 = "feeds"
    name                   = "JSON"
    url                    = "/feeds/feed.json"
    weight                 = 133

