[minify]
    disableCSS   = false
    disableHTML  = false
    disableJS    = false
    disableJSON  = false
    disableSVG   = false
    disableXML   = false
    minifyOutput = true
    [minify.tdewolff]
        [minify.tdewolff.html]
            keepConditionalComments = false
            keepDefaultAttrVals     = false
            keepDocumentTags        = true
            keepEndTags             = true
            keepWhitespace          = false

