# basic settings

config                      = "config.toml"
log                         =  true
verbose                     =  true
logFile                     = "hugo.log" 
verboseLog                  = "info.log"
ignoreFiles                 = [ "\\.cmd$", "\\.log$", "\\.bat$", "\\.tmp$" , "\\.swp$"]
timeout                     = 300000

#baseUrl                    = "http://localhost:1313"
disableKinds                = ["RSS", "sitemap"]
refLinksNotFoundURL        = "/404.html"

title                       = "G's Playground"
titleCaseStyle              = "Chicago"
theme                       = "photon"

###############################################################

LanguageCode                   = "de-de"
DefaultContentLanguage         = "de"
DefaultContentLanguageInSubdir = true
defaultExtension           = "html"
defaultLayout              = "post"

###############################################################

archetypedir               = "archetypes"
assetdir                   = "assets"
contentdir                 = "content"
dataDir                    = "data"
layoutdir                  = "layouts"
publishdir                 = "public"
paginatepath               = "page"
resourcedir                = "resources"
staticdir                  = "static"

###############################################################

buildDrafts                = false
buildExpired               = false
buildFuture                = false
canonifyURLs               = false
disableAliases             = false
cleandestinationdir        = true
disableHugoGeneratorInject = true
disablePathToLower         = false
enableRobotsTXT            = true
ignorecache                = false
forceSyncStatic            = false
#pluralizelisttitles       = false
relativeURLs               = false
removePathAccents          = true
summaryLength              = 10
taskLists                  = false


###############################################################

[frontmatter]
date                       = [ "date", ":filename", ":default"]
publishDate                = [ "publishDate", "date"]
lastmod                    = [ "lastmod", ":fileModTime", "publishDate"]
expiryDate                 = [ "expiryDate"]

###############################################################

[minify]
    disableCSS   = false
    disableHTML  = false
    disableJS    = false
    disableJSON  = false
    disableSVG   = false
    disableXML   = false
    minifyOutput = true
    [minify.tdewolff]
        [minify.tdewolff.html]
            keepConditionalComments = false
            keepDefaultAttrVals     = false
            keepDocumentTags        = true
            keepEndTags             = true
            keepWhitespace          = false

###############################################################

[markup]
    defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

###############################################################

[taxonomies]
    tag                    = "tags"
    serie                  = "series"
#   categorie NOT used!

[permalinks]
    post                   = "/:section/:year/:month/:day/:title"
    photo                  = "/:section/:year/:month/:day/:title"
    series                 = "/:section/:slug"
    tags                   = "/:section/:slug"
	about                  = "/:section/:slug"
    intern                 = "/:section/:year/:month/:day/:title"
    test                   = "/:section/:title"

###############################################################

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/rss+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/json"]
    suffixes               = ["json"]

  [mediaTypes."application/manifest+json"]
    suffixes              = ["webmanifest"]

[outputFormats.HTML]
    baseName               = "index"
    NoUgly                 = true
    IsHTML                 = true
    permalinkable          = true

[outputFormats.ATOM]
    MediaType              = "application/atom+xml"
    BaseName               = "feeds/feed.atom"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.FEED]       ##### ==> no collision with buildin RSS!
    MediaType              = "application/rss+xml"
    BaseName               = "feeds/feed.rss"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.JSON]
    MediaType              = "application/json"
    BaseName               = "feeds/feed"
    IsHTML                = false
    IsPlainText           = true
    noUgly                = false
    Rel                   = "alternate"

[outputFormats.SITEMAP]
    MediaType             = "application/xml"
    BaseName              = "sitemap"
    IsHTML                = false
    IsPlainText           = true
    noUgly                = true
    Rel                   = "sitemap"


[outputFormats.MANIFEST]
    MediaType             = "application/manifest+json"
    BaseName              = "manifest"
    suffix                = "webmanifest"
    IsHTML                = false
    IsPlainText           = true
    noUgly                = false
    Rel                   = "manifest"

[outputs]
    home                  = [ "HTML", "ATOM", "JSON", "FEED", "MANIFEST", "SITEMAP"]
    section               = [ "HTML", "SITEMAP" ]
    page                  = [ "HTML" ]
    taxonomy              = [ "HTML" ]
    taxonomyTerm          = [ "HTML" ]


###############################################################

[imaging]
    resampleFilter     = "Lanczos"
    quality            = 85
	bgColor            = "#ffffff"

[imaging.exif]
    includeFields = ".*"
    
[Author]
    name               = "Gerhard Junker"
    email              = "me@example.com"

###############################################################

[Params]
    title              = "My Playground"
    copyright          = "Mr. Nobody"
    copyrightyear      = "1972"
	published           = "2016-08-21T00:00:00Z"
    dateFormatLong      = "2006-01-02 15:04"
    dateFormatShort     = "2006-01-02"
    dateFormatYear      = "2006"
    dateFormatFeed      = "2006-01-02T15:04:05Z"
	dateFormatRFC822Z   = "02 Jan 2006 15:04:05 UT" 

    invisibleSections   = ["menu","serie","about", "links"]
	sitemapMax          = 49999

    feedSize               = 25 # rssLimit 
    digest                 = "sha384"
    
[Params.sidebar]
	avatar          = "/img/head.jpg"
	bio             = "**Mr. Nobody**"

[Params.Sitemap]
	changeFreq = "weekly"
	priority   = 0.5

[Params.Pagination]
    PagesPerList           = 10
    PagesPerListHome       = 10
    Paginate               = 10
    firstIndicator         = "<i class=\"fas fa-angle-double-left\"></i>"
    previousIndicator      = "<i class=\"fas fa-angle-left\"></i>"
    nextIndicator          = "<i class=\"fas fa-angle-right\"></i>"
    lastIndicator          = "<i class=\"fas fa-angle-double-right\"></i>"
    showBeginEnd           = false
    spaceIndicator         = "<b> ... </b>"
    pagesBetweenActive     = 5

################# Image handling ###########
# shortcode   figure.html
# render hook render-image.html

[Params.Images]
	maxSize                = 1480
    setSizes              = [ 480, 800, 1200 ]

###############################################################


[menu]
[[menu.main]]
    identifier          = "home"
    name                = "Startseite"
    url                 = "/"
    weight              = 10

[[menu.main]]
    identifier          = "post"
    name                = "Beiträge"
    url                 = "/post/"
    weight              = 20

[[menu.main]]
    identifier          = "photo"
    name                = "Fotos"
    url                 = "/photo/"
    weight              = 30

[[menu.main]]
    identifier          = "serie"
    name                = "Serien"
    url                 = "/series/"
    weight              = 40

[[menu.main]]
    identifier          = "link"
    name                = "Links"
    url                 = "/links/"
    weight              = 50

[[menu.main]]
    identifier          = "index"
    name                = "Index"
    url                 = "/tags/"
    weight              = 110

