# theme configuration

#disableKinds               = ["RSS", "sitemap"]

###############################################################


[markup]
  defaultMarkdownHandler = "goldmark"
  
### https://github.com/yuin/goldmark/#built-in-extensions

  [markup.goldmark]
    [markup.goldmark.extensions]
      autolinks      = false
      definitionList = false
      footnote       = true
      linkify        = true
      strikethrough  = true
      table          = true
      taskList       = false
      typographer    = true
      
    [markup.goldmark.parser]
#      autoHeadingID     = false
#      autoHeadingIDType = "github"
       withAttribute     = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        
    
################# Image handling ###########

# shortcode   figure.html
# render hook render-image.html

[Params.Images]
    maxSize               = 1480
    setSizes              = [ 480, 800, 1200 ]
    sizes                 = "sizes=(max-width: 30em) 90vw, (max-width: 60em) 80vw, 1480px"

###############################################################	

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/rss+xml"]
    suffixes               = ["xml"]

  [mediaTypes."application/json"]
    suffixes               = ["json"]

# search
  [mediaTypes."application/catalog+json"]
    suffixes               = ["json"]

  [mediaTypes."application/manifest+json"]
    suffixes               = ["webmanifest"]

[outputFormats.HTML]
    baseName               = "index"
    NoUgly                 = true
    IsHTML                 = true
    permalinkable          = true

[outputFormats.ATOM]
    MediaType              = "application/atom+xml"
    BaseName               = "feeds/feed.atom"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.FEED]       ##### ==> no collision with buildin RSS!
    MediaType              = "application/rss+xml"
    BaseName               = "feeds/feed.rss"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    Rel                    = "alternate"

[outputFormats.JSON]
    MediaType              = "application/json"
    BaseName               = "feeds/feed"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    Rel                    = "alternate"

[outputFormats.SITEMAP]
    MediaType              = "application/xml"
    BaseName               = "sitemap"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = true
    notAlternative         = true
    Rel                    = "sitemap"


[outputFormats.MANIFEST]
    MediaType              = "application/manifest+json"
    BaseName               = "manifest"
    suffix                 = "webmanifest"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    notAlternative         = true
    Rel                    = "manifest"

[outputFormats.SEARCH]
    MediaType              = "application/catalog+json"
    BaseName               = "search/search"
    IsHTML                 = false
    IsPlainText            = true
    noUgly                 = false
    notAlternative         = true
    Rel                    = "alternate"

[imaging]
    resampleFilter         = "Lanczos"
    quality                = 85
    bgColor                = "#ffffff"

[imaging.exif]
    includeFields = ".*"

[Params]
    published              = "2016-08-21T00:00:00Z"
    dateFormatLong         = "2006-01-02 15:04"
    dateFormatShort        = "2006-01-02"
    dateFormatYear         = "2006"
    dateFormatFeed         = "2006-01-02T15:04:05Z"
	dateFormatISO8601      = "2006-01-02T15:04:05-07:00" 
    dateFormatRFC822Z      = "02 Jan 2006 15:04:05 UT"

    invisibleSections      = ["feeds","intern","test","about","links","search"]
    sitemapMax             = 49999

    digest                 = "sha384" # sha256, sha384, sha512
	
[Params.Pagination]
    PagesPerList           = 10
    PagesPerListHome       = 12
    Paginate               = 10
    firstIndicator         = "<i class=\"fas fa-angle-double-left\"></i>"
    previousIndicator      = "<i class=\"fas fa-angle-left\"></i>"
    nextIndicator          = "<i class=\"fas fa-angle-right\"></i>"
    lastIndicator          = "<i class=\"fas fa-angle-double-right\"></i>"
    showBeginEnd           = false
    spaceIndicator         = "<b> ... </b>"
    pagesBetweenActive     = 5

[menus]
[[menus.main]]
    identifier             = "home"
    name                   = "Home"
    pageRef                = "home"
    weight                 = 10
    url                    = "/"

[[menus.main]]
    identifier             = "post"
    name                   = "Posts"
    pageRef                = "post"
    weight                 = 20

[[menus.main]]
    identifier             = "photo"
    name                   = "Photos"
    pageRef                = "photo"
    weight                 = 30

[[menus.main]]
    identifier             = "serie"
    name                   = "Series"
    url                    = "/series/"
    weight                 = 40

[[menus.main]]
    identifier             = "link"
    name                   = "Links"
    pageRef                = "link"
    weight                 = 100

[[menus.main]]
    identifier             = "tags"
    name                   = "Index"
    pageRef                = "tags"
    weight                 = 110

[[menus.main]]
    identifier             = "search"
    name                   = "Search"
    pageRef                = "search"
    weight                 = 110

[[menus.main]]
    identifier             = "feeds"
    name                   = "Feeds"
    pageRef                = "feeds"
    weight                 = 130

[[menus.main]]
	parent                 = "feeds"
    name                   = "ATOM"
    pageRef                = "/feeds/atom"
    weight                 = 1301

[[menus.main]]
	parent                 = "feeds"
    name                   = "RSS"
    pageRef                = "/feeds/rss"
    weight                 = 1302

[[menus.main]]
	parent                 = "feeds"
    name                   = "JSON"
    pageRef                = "/feeds/json"
    weight                 = 1303

